### ISSUE TITLE
Extra divide by 2 in display_output definition of ThreadArt

### ISSUE THREAD

**Issue by scminne** [bluemoon93/UsefulPi#2]
David,
I think this is a bug, if not, if you could explain I would appreciate it.

The purpose of display_output in ThreadArt, is to provide a text listing of the manual threading order. The hook number is the same as the numbers in the array of lines. Therefore, there is no need to divide by 2. 

Shouldn't the command simply be: output_number = f"{line[1]}" rather than having the divide by 2?

Thanks,
Steve

**Comment by david-simoes-93** [comment]
You're absolute right! This was fixed in 1c6c6eecb6925753ea2c58cf863b5df14bdde345

PS: sorry it took so long to reply, I didn't get a notification :/
